import React, { useEffect, useState } from 'react'
import { getOSEmployees } from '../../services/ose'
import { getResourcePlanners } from '../../services/resourcePlanner'

export default function PlannerPortfolio() {
  const [planner, setPlanner] = useState(null)
  const [hired, setHired] = useState([])
  useEffect(() => { Promise.all([getResourcePlanners(), getOSEmployees()]).then(([planners, employees]) => { const userId = Number(localStorage.getItem('userId')); const userName = localStorage.getItem('userName'); const current = (planners || []).find(item => item.user_ID === userId) || (planners || []).find(item => item.name?.toLowerCase().includes(userName?.toLowerCase() || '')) || planners?.[0]; setPlanner(current); setHired((employees || []).filter(item => item.status === 'Hired' && (!current || item.planner_ID === current.planner_ID))) }) }, [])
  return <div className="planner-content aaib-animate-fade"><div className="planner-page-head"><div><p className="planner-eyebrow">PERSONAL PORTFOLIO</p><h1>My portfolio</h1><p>Planner details and OS employees hired through your desk.</p></div></div><section className="aaib-panel planner-profile-card"><div className="planner-profile-avatar">{(planner?.name || 'RP').slice(0, 2).toUpperCase()}</div><div><p className="planner-eyebrow">RESOURCE PLANNER</p><h2>{planner?.name || 'Planner profile unavailable'}</h2><p>{planner?.email || 'Email not provided'} · {planner?.phone || 'Phone not provided'}</p></div></section><div className="planner-section-head"><div><p className="planner-eyebrow">PLACED TALENT</p><h2>OS employees hired</h2></div><span className="planner-count">{hired.length} placed</span></div>{hired.length ? <div className="planner-person-grid">{hired.map(item => <article className="aaib-panel planner-person-card" key={item.ose_ID}><div className="planner-person-avatar">{`${item.fN || ''}${item.lN || ''}`.slice(0, 2).toUpperCase()}</div><div><h3>{item.fN} {item.lN}</h3><p>{item.vendor || 'Vendor not provided'}</p><span className="aaib-badge aaib-badge-success">Hired</span></div></article>)}</div> : <div className="planner-empty aaib-panel">No hired OS employees are currently linked to this planner.</div>}</div>
}
