import React, { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { getOSEmployees } from '../../services/ose'
import { getResourcePlanners } from '../../services/resourcePlanner'

const statusClass = status => ({ Hired: 'aaib-badge-success', Selected: 'aaib-badge-warning', 'In Interview': 'aaib-badge-neutral', Rejected: 'aaib-badge-danger' }[status] || 'aaib-badge-neutral')

export default function PlannerDashboard() {
  const [employees, setEmployees] = useState([])
  const [planner, setPlanner] = useState(null)
  const [loading, setLoading] = useState(true)
  useEffect(() => { Promise.all([getOSEmployees(), getResourcePlanners()]).then(([ose, planners]) => { setEmployees(ose || []); const userName = localStorage.getItem('userName'); setPlanner((planners || []).find(item => item.user_ID === Number(localStorage.getItem('userId'))) || (planners || []).find(item => item.name?.toLowerCase().includes(userName?.toLowerCase() || '')) || planners?.[0]) }).finally(() => setLoading(false)) }, [])
  const hired = employees.filter(item => item.status === 'Hired')
  return <div className="planner-content aaib-animate-fade"><section className="planner-welcome"><div><p className="planner-eyebrow">RESOURCE PLANNING DESK</p><h1>Good morning, {planner?.name || localStorage.getItem('userName') || 'Planner'}</h1><p>Keep your OS pipeline moving from selection to placement.</p></div><div className="planner-welcome-mark">RP</div></section><div className="planner-stat-grid"><Link to="/planner/employees" className="aaib-panel planner-stat planner-stat-link"><span>OS employees</span><strong>{loading ? '—' : employees.length}</strong><small>Total pipeline · Open</small></Link><Link to="/planner/portfolio" className="aaib-panel planner-stat planner-stat-link"><span>Hired</span><strong>{loading ? '—' : hired.length}</strong><small>In your portfolio · Open</small></Link><Link to="/planner/employees" className="aaib-panel planner-stat planner-stat-link"><span>Needs attention</span><strong>{loading ? '—' : employees.filter(item => item.status === 'In Interview' || item.status === 'Selected').length}</strong><small>Active candidates · Open</small></Link></div><div className="planner-section-head"><div><p className="planner-eyebrow">PIPELINE SNAPSHOT</p><h2>Recent OS employees</h2></div><Link className="aaib-btn aaib-btn-secondary" to="/planner/employees">Manage pipeline</Link></div><div className="planner-table-wrap aaib-panel">{loading ? <div className="planner-empty">Loading employee pipeline...</div> : employees.length ? <table className="planner-table"><thead><tr><th>Name</th><th>Vendor</th><th>Status</th><th>Planner</th></tr></thead><tbody>{employees.slice(0, 6).map(item => <tr key={item.ose_ID}><td><strong>{item.fN} {item.lN}</strong><small>{item.email || 'No email provided'}</small></td><td>{item.vendor || '—'}</td><td><span className={`aaib-badge ${statusClass(item.status)}`}>{item.status || 'Unassigned'}</span></td><td>PLN-{item.planner_ID}</td></tr>)}</tbody></table> : <div className="planner-empty">No OS employees are in the pipeline yet.</div>}</div></div>
}
