import React, { useEffect, useState } from 'react'
import { createPlannerRequest, getPlannerRequests, getPORequests } from '../../services/resourceService'

export default function PlannerRequests() {
  const [incoming, setIncoming] = useState([])
  const [sent, setSent] = useState([])
  const [form, setForm] = useState({ department: 'Backend', count: 1, details: '' })
  const [message, setMessage] = useState('')
  const load = () => Promise.all([getPORequests(), getPlannerRequests()]).then(([po, planner]) => { setIncoming(po || []); setSent(planner || []) })
  useEffect(() => { load().catch(() => setMessage('Unable to load staffing requests.')) }, [])
  async function sendRequest(event) { event.preventDefault(); setMessage(''); try { await createPlannerRequest({ Department: form.department, Required_Count: Number(form.count), Details: form.details, Planner_ID: Number(localStorage.getItem('plannerId')) || null }); setForm({ department: 'Backend', count: 1, details: '' }); await load(); setMessage('Request sent to the Vertical Head.') } catch { setMessage('The request could not be saved.') } }
  return <div className="planner-content aaib-animate-fade"><div className="planner-page-head"><div><p className="planner-eyebrow">STAFFING COORDINATION</p><h1>PO requests</h1><p>Review staffing demand and send OS employee requests to Vertical Heads.</p></div></div><div className="planner-request-layout"><section><div className="planner-section-head"><div><p className="planner-eyebrow">INCOMING</p><h2>Requests requiring OS employees</h2></div></div>{incoming.length ? <div className="planner-request-list">{incoming.map(request => <article className="aaib-panel planner-request-card" key={request.request_ID}><div><strong>{request.required_Count} OS employee{request.required_Count > 1 ? 's' : ''} · {request.department}</strong><p>{request.details || 'No additional details.'}</p></div><span className="aaib-badge aaib-badge-warning">{request.status}</span></article>)}</div> : <div className="aaib-panel planner-empty"><strong>No incoming PO requests.</strong><p>Requests from Product Owners will appear here.</p></div>}<div className="planner-section-head planner-sent-heading"><div><p className="planner-eyebrow">OUTGOING</p><h2>Requests to Vertical Heads</h2></div></div>{sent.length ? <div className="planner-request-list">{sent.map(request => <article className="aaib-panel planner-request-card" key={request.request_ID}><div><strong>{request.required_Count} OS employee{request.required_Count > 1 ? 's' : ''} · {request.department}</strong><p>{request.details || 'No additional details.'}</p></div><span className="aaib-badge aaib-badge-warning">{request.status}</span></article>)}</div> : <div className="aaib-panel planner-empty">No outgoing requests yet.</div>}</section><form className="aaib-panel planner-request-form" onSubmit={sendRequest}><p className="planner-eyebrow">NEW REQUEST</p><h2>Ask a Vertical Head</h2><label>Department<select className="aaib-select" value={form.department} onChange={event => setForm({ ...form, department: event.target.value })}>{['Backend', 'Frontend', 'Tester', 'Product Owner', 'Scrum Master', 'UI/UX Design'].map(item => <option key={item}>{item}</option>)}</select></label><label>Required OS employees<input className="aaib-input" type="number" min="1" max="50" value={form.count} onChange={event => setForm({ ...form, count: event.target.value })} /></label><label>Relevant details<textarea className="aaib-textarea" placeholder="Skills, timing, or project context" value={form.details} onChange={event => setForm({ ...form, details: event.target.value })} /></label>{message && <div className="planner-feedback success">{message}</div>}<button className="aaib-btn aaib-btn-primary">Send request</button></form></div></div>
}
